"""add company_id to tenant models

Revision ID: 106a8143c808
Revises: df5270d35a20
Create Date: 2026-07-14 14:57:17.008287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106a8143c808'
down_revision: Union[str, None] = 'df5270d35a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_appointments_company_id'), 'appointments', ['company_id'], unique=False)
    op.add_column('clients', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.add_column('config', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_config_company_id'), 'config', ['company_id'], unique=False)
    op.add_column('conversations', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_conversations_company_id'), 'conversations', ['company_id'], unique=False)
    op.add_column('email_conversations', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_email_conversations_company_id'), 'email_conversations', ['company_id'], unique=False)
    op.add_column('email_messages', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_email_messages_company_id'), 'email_messages', ['company_id'], unique=False)
    op.add_column('notifications', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.add_column('tickets', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_tickets_company_id'), 'tickets', ['company_id'], unique=False)
    op.add_column('website_conversations', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_website_conversations_company_id'), 'website_conversations', ['company_id'], unique=False)
    op.add_column('website_messages', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_website_messages_company_id'), 'website_messages', ['company_id'], unique=False)
    op.add_column('website_visitors', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_website_visitors_company_id'), 'website_visitors', ['company_id'], unique=False)
    # ### end Alembic commands ###

    bind = op.get_bind()
    tables = [
        "clients",
        "conversations",
        "appointments",
        "tickets",
        "notifications",
        "config",
        "email_conversations",
        "email_messages",
        "website_visitors",
        "website_conversations",
        "website_messages",
    ]
    for table in tables:
        bind.execute(
            sa.text(f"UPDATE {table} SET company_id = 1 WHERE company_id IS NULL OR company_id = 0")
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_visitors_company_id'), table_name='website_visitors')
    op.drop_column('website_visitors', 'company_id')
    op.drop_index(op.f('ix_website_messages_company_id'), table_name='website_messages')
    op.drop_column('website_messages', 'company_id')
    op.drop_index(op.f('ix_website_conversations_company_id'), table_name='website_conversations')
    op.drop_column('website_conversations', 'company_id')
    op.drop_index(op.f('ix_tickets_company_id'), table_name='tickets')
    op.drop_column('tickets', 'company_id')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_column('notifications', 'company_id')
    op.drop_index(op.f('ix_email_messages_company_id'), table_name='email_messages')
    op.drop_column('email_messages', 'company_id')
    op.drop_index(op.f('ix_email_conversations_company_id'), table_name='email_conversations')
    op.drop_column('email_conversations', 'company_id')
    op.drop_index(op.f('ix_conversations_company_id'), table_name='conversations')
    op.drop_column('conversations', 'company_id')
    op.drop_index(op.f('ix_config_company_id'), table_name='config')
    op.drop_column('config', 'company_id')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_column('clients', 'company_id')
    op.drop_index(op.f('ix_appointments_company_id'), table_name='appointments')
    op.drop_column('appointments', 'company_id')
    # ### end Alembic commands ###
