"""add read and archived to conversations

Revision ID: 2c060afe81bb
Revises: 106a8143c808
Create Date: 2026-07-14 15:16:43.907792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c060afe81bb'
down_revision: Union[str, None] = '106a8143c808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('read', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.add_column('conversations', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived')
    op.drop_column('conversations', 'read')
    # ### end Alembic commands ###
