"""add companies and user company_id

Revision ID: df5270d35a20
Revises: d4e5f6a7b8c
Create Date: 2026-07-14 14:54:14.386767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5270d35a20'
down_revision: Union[str, None] = 'd4e5f6a7b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    # ### end Alembic commands ###

    bind = op.get_bind()
    bind.execute(sa.text("INSERT OR IGNORE INTO companies (id, name, created_at) VALUES (1, 'Empresa Padrão', datetime('now'))"))
    bind.execute(sa.text("UPDATE users SET company_id = 1 WHERE company_id IS NULL OR company_id = 0"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
